version: '3.8'

services:
  postgres:
    container_name: forum-db-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=forum-db
      - PGDATA=/data/postgres
  cache:
    container_name: forum-db-cache
    image: redis
    ports:
      - 6379:6379

